# Generated by Django 5.0.4 on 2025-05-03 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dorm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone', models.CharField(choices=[('A', 'โซนเจปาร์ค'), ('B', 'โซนเชียงราก 1'), ('C', 'โซนเชียงราก 2'), ('D', 'โซนดีเคฟ'), ('E', 'โซนดีคอนโด'), ('F', 'โซนซันต้า'), ('G', 'โซนทียูโดม'), ('H', 'โซนกอล์ฟวิว')], max_length=1)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=100)),
                ('price_per_month', models.DecimalField(decimal_places=2, max_digits=8)),
                ('size_sqm', models.IntegerField(blank=True, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('dorm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_types', to='product_management.dorm')),
            ],
        ),
        migrations.CreateModel(
            name='RoomImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField()),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='product_management.roomtype')),
            ],
        ),
    ]
