# Generated by Django 5.0.4 on 2025-05-04 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0003_alter_roomimage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomimage',
            name='image',
        ),
        migrations.AddField(
            model_name='roomimage',
            name='image_url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='DormImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(blank=True, null=True)),
                ('dorm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='product_management.dorm')),
            ],
        ),
    ]
