# Generated by Django 5.0.4 on 2025-05-06 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0004_remove_roomimage_image_roomimage_image_url_dormimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='dorm',
            name='location_embed',
            field=models.TextField(blank=True, null=True),
        ),
    ]
