services:
  db:
    image: postgres:15
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=cn334Admin
      - POSTGRES_PASSWORD=cn334Admin
    ports:
      - "5433:5432"

  product_api:
    build: ./product_service
    command: python manage.py runserver 0.0.0.0:8888
    volumes:
      - ./product_service:/code
      - ./product_service/media:/code/media 
    ports:
      - "3341:8888"
    env_file: .env 
    environment:
      DB_HOST: db
      POSTGRES_NAME: postgres
      POSTGRES_USER: cn334Admin
      POSTGRES_PASSWORD: cn334Admin
    depends_on:
      - db
  user_api:
    build: ./user_service
    command: python manage.py runserver 0.0.0.0:8888
    volumes:
      - ./user_service:/code
    ports:
      - "3342:8888"
    env_file: .env 
    environment:
      DB_HOST: db
      POSTGRES_NAME: postgres
      POSTGRES_USER: cn334Admin
      POSTGRES_PASSWORD: cn334Admin
    depends_on:
      - db
  frontend:
    build:
      context: ./app_frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - user_api
      - product_api